### ISSUE TITLE
Call to undefined function lzf_decompress() on line 704

### ISSUE THREAD

**Issue by lawrencetaur** [colinmollenhour/magento-cache-benchmark#3]
I get this error when i run php shell/cache-benchmark.php init on magnento root(which is domain.com/web/ folder)

PHP Fatal error:  Call to undefined function lzf_decompress() in /var/www/www.domain.com/web/.modman/Cm_Cache_Backend_Redis/Cm/Cache/Backend/Redis.php on line 704

**Comment by colinmollenhour** [comment]
You're missing the lzf extension somehow. Perhaps a php.ini issue.
